# Generated by Django 2.1.5 on 2019-02-17 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Time')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('successful', models.BooleanField(default=False, verbose_name='Successful')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL,
                                           verbose_name='User')),
            ],
        ),
    ]
